name: CI

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  main:
    name: Python ${{ matrix.python }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12", "3.13", "pypy3.9", "pypy3.10"]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5.1.1
        with:
          python-version: ${{ matrix.python }}
          allow-prereleases: true
      - run: python -m pip install coverage tox
      - run: python -m tox
      - uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673 # v4.5.0
        with:
          name: ${{ matrix.python }}
          token: ${{ secrets.CODECOV_TOKEN }}
